### ISSUE TITLE
Ordine parole in PDF

### ISSUE THREAD

**Issue by fvalle1** [taringamberini/diceware_word_list_it-IT#1]
Posso suggerire di generare il PDF delle parole in modo che, come nella lista originale, ci sia un numero per ogni pagina..
Esempio a pagina 1 tutte le parole con 11...
Pagina 2
12...
Sarebbe comodo anche un numero per ogni colonna
Esempio pagina 1

111...|112...|113...|114...|115...|116...
In modo da avere 36 parole per colonna!

Sarebbe molto comodo cercare le parole...

**Comment by taringamberini** [comment]
Great hints, I'll update the [PDF format](http://www.taringamberini.com/it/diceware_it_IT/lista-di-parole-diceware-in-italiano/) in the short term.

**Comment by taringamberini** [comment]
@fvalle1 What about numbering pages accordingly with the first 2 dices?

Something like:

    ---------------------------------------------------------------------------------------

    11111 0        11211 36       11311 72       11411 333      11511 1960     11611 2468
    ...
    11166 35       11266 71       11366 300      11466 1955     11566 2345     11666 %%
    pag. 11 (real page 1)

    ---------------------------------------------------------------------------------------

    12111 %%%      12211 abbina   12311 accaso   12411 addio    12511 afa      12611 agiato
    ...
    12166 abbia    12266 accasi   12366 addii    12466 af       12566 agiate   12666 albina

    pag. 12 (real page 2)

    ---------------------------------------------------------------------------------------
    ...
    ---------------------------------------------------------------------------------------

    66111 voi      66211 vorrei   66311 wi       66411 xp       66511 yw       66611 zj       
    ...
    66166 vorrai   66266 wh       66366 xo       66466 yv       66566 zitto    66666 zzzz     

    pag. 66 (real page 36)

    ---------------------------------------------------------------------------------------

**Comment by fvalle1** [comment]
It should be a great idea!


Il giorno 17/dic/2015, alle ore 00.14, Tàrin Gamberìni ha scritto:

**Comment by taringamberini** [comment]
Available on my blog the new Italian words list: [Lista di parole Diceware in italiano](http://www.taringamberini.com/it/diceware_it_IT/lista-di-parole-diceware-in-italiano/).

As soon as I'll commit it on github.

Nice dicewering!

**Comment by fvalle1** [comment]
What a good news!!

Thanks:-)

Filippo

**Comment by fvalle1** [comment]
be careful!

the pdf signature file http://www.taringamberini.com/downloads/diceware_it_IT/lista-di-parole-diceware-in-italiano/2/word_list_diceware_it-IT-2.pdf.sig is unreachable...


Filippo

Il giorno 28/dic/2015, alle ore 18.12, Tàrin Gamberìni ha scritto:

**Comment by taringamberini** [comment]
> the pdf signature file http://www.taringamberini.com/downloads/diceware_it_IT/lista-di-parole-diceware-in-italiano/2/word_list_diceware_it-IT-2.pdf.sig is unreachable...

Fixed.

Thanks,
Tarin
